name: Build and Push Docker Image

on:
  push:
    branches:
      - main  # Defina a branch que acionará o workflow

jobs:
  build-and-push:
    runs-on: ubuntu-latest  # Pode escolher outro ambiente, como macOS ou Windows

    steps:
      - name: Checkout code
        uses: actions/checkout@v2

      - name: Login to Docker Hub
        run: |
          docker login -u ${{ secrets.DOCKERHUB_USERNAME }} -p ${{ secrets.PASSWORD }}
          docker build -t iagomauricio/nginx-templates:01 .
          docker push iagomauricio/nginx-templates:01